version: "3.8"

services:
  namenode:
    build:
      context: hadoop
      target: build_hadoop
    hostname: namenode
    # Сначала запусти меня
    # command: ["hdfs", "namenode", "-format", "-force"]
    # А уже потом спокойно запускай меня
    command: [ "hdfs", "namenode" ]
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"
    volumes:
      - hadoop_namenode:/tmp/hadoop-root/
      - ./hadoop_conf/etc:/opt/hadoop/etc

  datanode1:
    build:
      context: hadoop
      target: build_hadoop
    hostname: datanode1
    command: [ "hdfs", "datanode" ]
    env_file:
      - hadoop.env
    ports:
      - "9864:9864"
    volumes:
      - hdfs1:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  datanode2:
    build:
      context: hadoop
      target: build_hadoop
    hostname: datanode2
    command: [ "hdfs", "datanode" ]
    env_file:
      - hadoop.env
    ports:
      - "9865:9864"
    volumes:
      - hdfs2:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  datanode3:
    build:
      context: hadoop
      target: build_hadoop
    hostname: datanode3
    command: [ "hdfs", "datanode" ]
    env_file:
      - hadoop.env
    ports:
      - "9866:9864"
    volumes:
      - hdfs3:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  resourcemanager:
    build:
      context: hadoop
      target: build_hadoop
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - "8088:8088"
    volumes:
      - resourcemanager:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  nodemanager1:
    build:
      context: hadoop
      target: build_hadoop
    hostname: nodemanager1
    command: [ "yarn", "nodemanager" ]
    ports:
      - "19888:19888"
      - "8042:8042"
    expose:
      - 19888
      - 8042
    volumes:
      - nodemanager1:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  nodemanager2:
    build:
      context: hadoop
      target: build_hadoop
    hostname: nodemanager2
    command: [ "yarn", "nodemanager" ]
    ports:
      - "19889:19888"
      - "8043:8042"
    expose:
      - 19888
      - 8042
    volumes:
      - nodemanager2:/tmp/hadoop-hadoop
      - ./hadoop_conf/etc:/opt/hadoop/etc

  jupyter:
    build:
      context: hadoop
      target: jupyter_hadoop
    env_file:
      - hadoop.env
    ports:
      - "8888:8888"
    volumes:
      - jupyter:/opt/notebooks
      - ./hadoop_conf/etc:/opt/hadoop/etc
    command: [ "jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0" ]

networks:
  default:
    name: yohoho

volumes:
  hdfs1:
  hdfs2:
  hdfs3:
  nodemanager1:
  nodemanager2:
  resourcemanager:
  hadoop_namenode:
  jupyter:
